{
 "title": "Huawei Dorado",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"snmp-dorado\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hwInfoPowerHealthStatus{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "hwInfoDiskType{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoDiskHealthStatus{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoDiskRunTime{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoDiskCapacity{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoDiskTemperature{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoDiskCapacityUsage{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoDiskLocation{instance='$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "basic information",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deviceId{instance=\"$instance\"}",
     "legendFormat": "SN: {{deviceId}} "
    },
    {
     "expr": "deviceId{instance=\"$instance\"}",
     "legendFormat": " HOSTNAME: {{hostname}}"
    },
    {
     "expr": "deviceId{instance=\"$instance\"}",
     "legendFormat": "IP {{instance}}"
    }
   ]
  },
  {
   "title": "Model name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deviceType{instance='$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "table",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "hwPerfPortDelay{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoPortEthHealthStatus{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoPortEthLostPackages{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoPortEthRunningStatus{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoPortEthType{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwPerfPortLocation{instance='$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "usedCapacity{instance='$instance'}",
     "legendFormat": "Used Capacity"
    },
    {
     "expr": "totalCapacity{instance='$instance'}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Status controllers",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "hwInfoControllerHealthStatus{instance='$instance'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwInfoControllerRole{instance='$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hwInfoControllerCPUUsage{instance=\"$instance\"}",
     "legendFormat": "CTE{{hwInfoControllerID}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hwInfoControllerMemoryUsage{instance=\"$instance\"}",
     "legendFormat": "CTE{{hwInfoControllerID}}"
    }
   ]
  },
  {
   "title": "Port read traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(hwPerfPortReadTraffic{instance='$instance'})",
     "legendFormat": "Total"
    },
    {
     "expr": "hwPerfPortReadTraffic{instance='$instance'} * on(hwPerfPortObjectId) group_left(hwPerfPortLocation) (hwPerfPortLocation != 0)",
     "legendFormat": "{{hwPerfPortLocation}}"
    }
   ]
  },
  {
   "title": "Port Write traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 35 },
   "targets": [
    {
     "expr": "sum(hwPerfPortWriteTraffic{instance='$instance'})",
     "legendFormat": "Total"
    },
    {
     "expr": "hwPerfPortWriteTraffic{instance='$instance'} * on(hwPerfPortObjectId) group_left(hwPerfPortLocation) (hwPerfPortLocation != 0)",
     "legendFormat": "{{hwPerfPortLocation}}"
    }
   ]
  },
  {
   "title": "TOTAL IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(hwPerfNodeTotalIOPS{instance='$instance'})",
     "legendFormat": "Total for all node"
    },
    {
     "expr": "hwPerfNodeTotalIOPS{instance='$instance'}",
     "legendFormat": "Total for node {{hwPerfNodeIfIndex}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "sum(hwPerfNodeWriteIOPS{instance='$instance'})",
     "legendFormat": "Write for node all node"
    },
    {
     "expr": "hwPerfNodeWriteIOPS{instance='$instance'}",
     "legendFormat": "Write for node {{hwPerfNodeIfIndex}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(hwPerfNodeReadIOPS{instance='$instance'})",
     "legendFormat": "Read for node all node"
    },
    {
     "expr": "hwPerfNodeReadIOPS{instance='$instance'}",
     "legendFormat": "Read for node {{hwPerfNodeIfIndex}}"
    }
   ]
  }
 ]
}